### ISSUE TITLE
Conflict with requireJs

### ISSUE THREAD

**Issue by david-soyez** [skandasoft/browser-plus#10]
The requireJs global variable "require" is overwritten, my website is not working.

**Comment by skandasoft** [comment]
Add config for preview..which does the jquery injection...so switch if off and you should have the problem.but if you needed preview the you need allow some code. check the latest commit.

**Comment by david-soyez** [comment]
I'm sorry I don't understand what you are talking about

**Comment by skandasoft** [comment]
Go to the settings  for the browsersplus package  and switch off preview

**Comment by david-soyez** [comment]
it's not working either 

Uncaught TypeError: undefined is not a function  require.config()

**Comment by skandasoft** [comment]
is there a website..that I can look at to replicate the issue..

**Comment by skandasoft** [comment]
grouping all the module issues..https://github.com/skandasoft/browser-plus/issues/18
