### ISSUE TITLE
Dirty global enviroment

### ISSUE THREAD

**Issue by lutherism** [skandasoft/browser-plus#11]
Currently apps get run in a contaminated context. Global variables such as "module" and "jQuery" which don't exist in Chrome, are within scope.

This is especially a problem for UMD modules inside apps which expect global exports. Because UMD detects that `module` is defined it will export CommonJS instead of the expected global behavior.

**Comment by lutherism** [comment]
relates to https://github.com/skandasoft/browser-plus/issues/10

**Comment by skandasoft** [comment]
Add config for preview..which does the jquery injection...so switch if off and you should have the problem.but if you needed preview the you need allow some code. check the latest commit.

**Comment by skandasoft** [comment]
Grouping all module issues...https://github.com/skandasoft/browser-plus/issues/18
