### ISSUE TITLE
Dark background  

### ISSUE THREAD

**Issue by VineshReddy** [skandasoft/browser-plus#110]
When I run Browser-plus im getting a dark background instead of white background in browser-plus.

![new](https://cloud.githubusercontent.com/assets/13883653/17830794/3fde7b5a-66f4-11e6-99fd-f3cd2b6fbfee.png)

Atom version : 1.9.9
Browser plus version : 0.0.76

**Comment by idontlikeregex** [comment]
experiencing this as well on mac osx
Atom version : 1.9.9
Browser plus version : 0.0.76

**Comment by NIck-Seong** [comment]
I get the same with you (atom: 1.9.9, browser-plus: 0.0.76, windows 10)

Try to modify `browser-plus.less` file (in browser-plus packages's styles folder)
Add `background-color: white` to the `webview`

```
div.browser-plus webview {
  height: 100%;
  background-color: white;
}
```

**Comment by NIck-Seong** [comment]
I get the same with you (atom: 1.9.9, browser-plus: 0.0.76, windows 10)

modify `browser-plus.less` file (in browser-plus packages's styles folder)
add `background-color: white` to the `webview`  

```
div.browser-plus webview {
  height: 100%;
  background-color: white;
}
```

**Comment by wildsidevt** [comment]
Thanks @Nick-Seong. I was having the same problem, as well. This edit worked!

**Comment by VineshReddy** [comment]
Thanks @Nick-Seong
