### ISSUE TITLE
Q: Replacement of `localhost` with `127.0.0.1`?

### ISSUE THREAD

**Issue by seangenabe** [skandasoft/browser-plus#112]
Why is `localhost` being replaced with `127.0.0.1`? IMO this work should be done by the OS's DNS and not explicitly hardcoded.

**Comment by skandasoft** [comment]
I know but this is webview..not sure if localhost will work.

**Comment by manulaiko** [comment]
@skandasoft localhost resolving is handled by the DNS and the *hosts* file, there's no way it can affect the behavior of the plugin.

**Comment by skandasoft** [comment]
check the latest patch ....
