### ISSUE TITLE
Solved - Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by skandasoft** [skandasoft/browser-plus#113]
If you have the above issue. Here are few of ways to solve.

try running apm rebuild-module-cache (Thanks to @jennuine in #98)
or

Copy node_modules/jquery-ui from the repo directly into ~/.atom/packages/browser-plus/node_modules/(Thanks to @jayjun in #98)
or

Clone the repo into ~/.atom/packages/ then running cd browser-plus && npm install(Thanks to @cpitkin in #98).

**Comment by dleen** [comment]
Why does the project not have a dependency on jquery-ui in package.json? Would this not fix the issue?

**Comment by dleen** [comment]
Adding jquery-ui as a dependency works fine for me so I opened a PR:

https://github.com/skandasoft/browser-plus/pull/115

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
