### ISSUE TITLE
is it possible to view localhost 

### ISSUE THREAD

**Issue by sononix** [skandasoft/browser-plus#13]
http://localhost:8080 seems to bring up a google search

**Comment by Mouq** [comment]
Can confirm issue; can be worked around by typing "http://127.0.0.1:8080/"

**Comment by skandasoft** [comment]
you can try localhost:8080..should work that way.

**Comment by dodekeract** [comment]
@skandasoft That workaround didn't work for me, also: what about TLS? Without HTTP(S) browser-plus can't really know if it should use TLS or not.
