### ISSUE TITLE
Think browser-plus is the plug-in that collides with terminal-plus

### ISSUE THREAD

**Issue by hkimlist** [skandasoft/browser-plus#132]
Hi,

Love this plug-in and also terminal-plus. Terminal-plus uses Ctrl-` (control-backtick) to toggle terminals. Once a terminal is open, there are also hide and maximize buttons.

Ctrl-` seems to work fine for terminals if I have no browser-plus tabs open. Once I have a browser-plus tab open, then Ctrl-` will open a terminal but no longer toggle it closed. Even the hide button on the terminal will no longer work.

I have done testing with and without browser-plus for a while and this seems to me the problem. I also have this problem on both Windows 7 and Mac 10.11.

Hong

**Comment by hkimlist** [comment]
Oh - forgot to mention that terminal-plus has a few variations like <something>-ide-terminal and termination packages. All terminal packages seem to have same behavior. I am currently using termination.

**Comment by zhyack** [comment]
Same problem, Windows 10, atom 1.12.9, platformio-ide-terminal 2.2.2(forked from terminal-plus). 
There may be issues either in browser-plus or in terminal-plus, for I have encountered the same problem when I used only terminal-plus a year ago(so I turned to use platformio-ide-terminal, which works perfect). I really love both packages, and I suggest someone looking into this problem if possible.

**Comment by skandasoft** [comment]
I am on https://atom.io/packages/platformio-ide-terminal - 2.4.0..and using it with browser-plus latest patch...looks ok
