### ISSUE TITLE
Enhance localhost URL

### ISSUE THREAD

**Issue by manulaiko** [skandasoft/browser-plus#133]
I have set up my Apache server to work with multiple virtual hosts. This means that I don't only have a localhost, instead I have an entry on */etc/hosts* for each virtual host pointing at *127.0.0.1*.

When trying to go to *http://localhost/* in the browser, the url is actually replaced with *http://127.0.0.1/*, I don't know what's the propose of it.

But what happens when you try to go to any of the entries of */etc/hosts*? You'll get redirected to a google search of it, no matter if you force it to be an URL of writing *http://project/* instead of just *project*.

It would be nice to don't force the google search if the URL starts with *http;//([a-zA-Z0-9]\*)/* and don't replace *http://localhost/* with *http://127.0.0.1/*

**Comment by skandasoft** [comment]
check the latest patch..
