### ISSUE TITLE
ToggleURLBar command toggles the url bars of all windows

### ISSUE THREAD

**Issue by NekuSoul** [skandasoft/browser-plus#135]
When hiding/showing the url bar with the toggleURLBar command it also hides/shows the URL bars of all other browser windows.

For example when window "BrowserA" has a hidden URL bar and then a new window "BrowserB" is opened (which has the URL bar visible by default), upon hiding the URL bar of "BrowserB" the URL bar of "BrowserA" reappears.

The toggleURLBar command should either only toggle the URL bar visibility of the current window or keep the visibility status synced across all browser windows.

**Comment by skandasoft** [comment]
fixed..
