### ISSUE TITLE
How to merge pythontutor.com with broweser-plus and the text editor in Atom?

### ISSUE THREAD

**Issue by mda6** [skandasoft/browser-plus#136]
I posted something similar on stack but with no answers.. 

I am pretty new into programing and Atom...Though i have some gut feeling that pythontutor.com could be easily integrated to work with Atom together with the browser-plus, since Atom is built on web technologies and pythontutor.com allows embeding of both step by step and the live modes which are pretty awesome. I have this imagined like split screen in atom. As you write, the code updates on the pythontutor.com

I tried doing this myself.. but when i looked into the coffee scripts and stuff it was just scary! I only know little bit of Python.. ;(

Thank you

**Comment by skandasoft** [comment]
just checked..you can still run it from the browser-plus
