### ISSUE TITLE
Option to open in new [normal editor] tab instead of new pane

### ISSUE THREAD

**Issue by danielbayley** [skandasoft/browser-plus#137]
This is the behaviour of _[atom-webbrowser]_, which is better IMO as it is much more like a regular browser window.

[atom-webbrowser]: https://atom.io/packages/atom-webbrowser

**Comment by Hellman2741** [comment]
Fixed in #146 
Don't worry about the first pull request, had to delete that one.

**Comment by skandasoft** [comment]
added a option for new tab..thanks @Pyragon
