### ISSUE TITLE
Window hashes are not added.

### ISSUE THREAD

**Issue by Pyragon** [skandasoft/browser-plus#147]
Lots of websites use hashes to scroll to certain positions in webpages, to remember what tab user's are on after a refresh, etc.

These hashes are not added into the address bar of browser-plus, and therefor are lost when you try to refresh the page.

URL bar refreshes but does not show/include hash.

![image](https://cloud.githubusercontent.com/assets/10274309/25526426/4b5b9be0-2bc8-11e7-9e62-f74d13c3b8bc.png)

**Comment by Pyragon** [comment]
Started working at one point, stopped again though.
Trying to figure out what caused it to work for a second...

**Comment by skandasoft** [comment]
closing this as I will track it from https://github.com/skandasoft/browser-plus/issues/139
