### ISSUE TITLE
Open url with self-signed SSL cert

### ISSUE THREAD

**Issue by KORN1UX** [skandasoft/browser-plus#150]
Hi, I have an issue with opening urls with self-signed SSL (ex. localhost https) - it just redirecting to HTTP. Any ideas?

**Comment by skandasoft** [comment]
I cannot recreate this as I don't have local https/ how to create a self certificate..any direction would help..

**Comment by KORN1UX** [comment]
It's like not correct SSL (ex. net::ERR_CERT_COMMON_NAME_INVALID). For example: pfSence generated certs, or something like that.

**Comment by skandasoft** [comment]
tracking from https://github.com/skandasoft/browser-plus/issues/72
