### ISSUE TITLE
CTRL + F5

### ISSUE THREAD

**Issue by JohnRobson** [skandasoft/browser-plus#157]
I need to force the Cache to Refresh to be able to update a page with several scripts.

Works fine in Google Chrome and Firefox AFTER the "CTRL + F5".

Please, could you add a option to throw out the cache and request a new?

Thank You.

ps.: I'm using the latest version.

**Comment by skandasoft** [comment]
doesn't the refresh load the new script that is new?

**Comment by JohnRobson** [comment]
no, that refresh is like an F5, won't update to the new script, is necessary something that clean the cache and reload everything again, like CTRL+F5.

**Comment by skandasoft** [comment]
added the ctrl+f5 /f5 to refresh

**Comment by JohnRobson** [comment]
Is working, thank you very much. Just to confirm, CTRL+Click is the same than CTRL+F5? (and Click = F5)
