### ISSUE TITLE
How does the Live Preview works?

### ISSUE THREAD

**Issue by DinisCruz** [skandasoft/browser-plus#20]
Is it able to sync the browser with code changes?

For example on an AngularJs app?

**Comment by skandasoft** [comment]
currently you should be open the url/file path on the browser path. for Filepath (file://whateverpath.html)
. and click on the live button(the lighting icon on the toolbar) and as you type on the editor and click save you should see the update on the browser-plus.

I am currently updating the preview-plus atom package...and browser plus ideally should be a plugin for that..This basically opens a lot of possiblities..keep watching..

**Comment by santosh** [comment]
I can neither see Live Button, nor any toolbar in my version of Atom. It's Atom 1.0.3 on Ubuntu 14.04 LTS.

**Comment by santosh** [comment]
Okay, I followed CTRL + ALT + O to open the browser. Now I don't get live preview of the file on clicking the lightning button. :confused:

**Comment by skandasoft** [comment]
you should be able to open a browser using browser-plus:open command. and you see in the toolbar

![image](https://cloud.githubusercontent.com/assets/9875379/9084905/b4414da8-3b3d-11e5-84eb-e2b7b43f57e5.png)

you should see the lightning button. if you opened a file/url and clicked on the lightning button you see it turn green...from there on what ever change you make on the file using the editor and clicking on save would have a live preview...

you can also check the preview-plus package(http://atom.io/packages/preview-plus) if you are looking for the hyper live(type and see preview )

**Comment by santosh** [comment]
First of all. When I do CTRL-T and search for `browser-plus:open` command, it doesn't shows up in fuzzy finder (CTRL + ALT + O brings the browser though).

Even if browser opens, it opens the homepage defined. Not the current working file.

**Comment by skandasoft** [comment]
may be the browser package is what you have..can you uninstall that package and reinstall browser-plus. 
yes it brings the home page every time..you need to add the file name to the url input box as shown in the prev answer. 
if you wanted to see the live preview of the file that is open...check the preview-plus package
