### ISSUE TITLE
unordered javascript loading

### ISSUE THREAD

**Issue by virtax** [skandasoft/browser-plus#23]
Many sites can't be properly loaded inside browser-plus, since order of loading javascript is unusual. 

For example:
1) on simple site theautolabs.com jQuery defined to load before application.js, but was loaded after application.js. This is lead to 'Uncaught ReferenceError: $ is not defined' error.
2) something similar was happened on github.com - "Uncaught TypeError: Cannot read property 'find' of undefined" - github can't load jQuery before another script
3) the same on www.linkedin.com
No such issues with loading the sites in desktop browsers. 

Atom Version: 1.0.2
System: Mac OS X 10.10.4
Package: browser-plus package, v0.0.29

**Comment by skandasoft** [comment]
This is a know issue and  being tracked with the https://github.com/skandasoft/browser-plus/issues/18
