### ISSUE TITLE
Lil Lonely Square Bracket

### ISSUE THREAD

**Issue by Toltar** [skandasoft/browser-plus#24]
![capture](https://cloud.githubusercontent.com/assets/6003536/8891184/e3350372-32e4-11e5-9df0-1b57edc8338c.PNG)

**Comment by skandasoft** [comment]
Will Try to Fix it with next release. Till then it has to stay there ALONE.. :)

**Comment by Toltar** [comment]
NOO your making it suffer!! Kill it before it suffers any longer! Lol jk :)

**Comment by skandasoft** [comment]
Yes..it is gone

**Comment by Toltar** [comment]
RIP lil square bracket
