### ISSUE TITLE
Security Nightmare?

### ISSUE THREAD

**Issue by jprichardson** [skandasoft/browser-plus#25]
Please correct me if I'm wrong, but doesn't this https://github.com/skandasoft/browser-plus/blob/v0.0.30/lib/browser-plus-view.coffee#L42 make this Atom package a security nightmare? It's probably not a huge concern right now given that `browser-plus` adoption compared to other browsers is minimal. But, all it would take is for some rogue webpage to `require('fs')`. 

It'd seem that the prudent solution would be to remove `nodeintegration`. Or at minimum, put a note in the README.

**Comment by skandasoft** [comment]
All I see is ttis plugin is mostly for checking the documenation with navigate package and quick/live preview in a browser environment. ...I will go ahead and add the details about Node-Integeration ON in the read me...

**Comment by skandasoft** [comment]
looks like it is a security nightmare..and I have the node-integeration as optional and switched off by default...updated readme..file.
