### ISSUE TITLE
Jquery isn't working

### ISSUE THREAD

**Issue by helloncanella** [skandasoft/browser-plus#26]
I've been experiencing problems when I attach jQuery to my projects.

The console report is the '$' isn't defined.

**Comment by skandasoft** [comment]
Please check the new version...This is all part of the node integeration issue being tracked in https://github.com/skandasoft/browser-plus/issues/18

**Comment by helloncanella** [comment]
I've downloaded it today, via atom. Isn't it the newest?

**Comment by skandasoft** [comment]
there was new patch released...apm update browser-plus or click on the updates on the right corner of the editor

**Comment by helloncanella** [comment]
It's working. Thank you.

**Comment by helloncanella** [comment]
Just now I realized the jQuery isn't working yet, even with the update.

**Comment by helloncanella** [comment]
I've said it was working because I hadn't compiled my .coffee

**Comment by helloncanella** [comment]
the last update solved the problem. Thanks

**Comment by sudofx** [comment]
I am still seeing this issue.

**Comment by sudofx** [comment]
It seems turning off "node integration" in the package settings seems to resolve this.

**Comment by hawkins** [comment]
@sudofx  I am experiencing the same issue as you. If I disable node integration, close browser plus panel, and reopen the preview then JQuery will work. However, JQuery will not work with node integration enabled.
