### ISSUE TITLE
many features don't support win10...

### ISSUE THREAD

**Issue by yzhen123** [skandasoft/browser-plus#27]
like select, history and Favoritize...

**Comment by skandasoft** [comment]
you need to switch on the node integeration in the settting/config for browser plus..

hope I can find sometime to rewrite some of these to be achieved without node-integeration..

**Comment by yzhen123** [comment]
still not working...

**Comment by skandasoft** [comment]
looks like there are issues..will fix ...soooon

**Comment by skandasoft** [comment]
finally found some time..fixed most of the stuff check it out

**Comment by yzhen123** [comment]
@skandasoft but unfortunately I have changed my labtop's system to deepin linux :+1:

**Comment by yzhen123** [comment]
Er...it appears that these features don't works well in linux too..

**Comment by skandasoft** [comment]
can you post a screenshot of what is happening. also can  you try the most updated version

**Comment by skandasoft** [comment]
would be happy to hear the feedback. Since I don't see any, assuming things are fixed. feel free to reopen

**Comment by yzhen123** [comment]
I'm sorry that I didn't reply these days... I update this morning and got some error.. I'll create a new issue
