### ISSUE TITLE
Keybindings for this browser

### ISSUE THREAD

**Issue by Rdbllx** [skandasoft/browser-plus#28]
Hello, thank's for this awesome package.
I wanted to know if it is possible to insert some keybindings 
like on chrome ?
Thank's in advance for your answers

**Comment by skandasoft** [comment]
for all the icons on the browser you should be able to tie to a keys..for eg f12 for developer tool..let me know if I answered your question..

**Comment by Rdbllx** [comment]
Ok thanks :)
