### ISSUE TITLE
Developer tools isn't working

### ISSUE THREAD

**Issue by helloncanella** [skandasoft/browser-plus#29]
Hi.

For some reason the developer tools arent working.

Thank you for the attention.

**Comment by skandasoft** [comment]
was it working previously and it stopped working? with the focus on browser try pressing f12/icon for developer tool at the end..

can you send the screen shot / steps to repeat..

**Comment by helloncanella** [comment]
![aqui](https://cloud.githubusercontent.com/assets/6288484/9432783/b7766ede-49fe-11e5-9556-9d3f908c3259.png)

As you can see, there isn't any preview for the browser-plus.

**Comment by skandasoft** [comment]
Are you able to get the developer tool in the regular atom.  also to set it as a normal tab might not be possible unless it is possible with the developer tool in the regular atom. This is might be a question for atom editor to be able to see it as a another tab.
