### ISSUE TITLE
Live JavaScript Broken

### ISSUE THREAD

**Issue by sinithwar** [skandasoft/browser-plus#39]
It doesn't seem like JavaScript itself is broken, because the result shows up properly when I first open the open-browser-plus. However, when I click on live, my JavaScript disappears.

**Comment by sinithwar** [comment]
This had previously worked just before I updated, so it's likely something to do with the new code you put in.

**Comment by sinithwar** [comment]
https://drive.google.com/file/d/0B5CT0bRL4CxAeUF1UGlyNG4tNE0/view?usp=sharing

**Comment by skandasoft** [comment]
I see from the screenshot you shared..you don't have the latest. can you try with the updated version. I will also check what is happening.

**Comment by sinithwar** [comment]
lol :) No, this happened after the update.
https://drive.google.com/file/d/0B5CT0bRL4CxALVJJZTRtQ2JzWU0/view?usp=sharing

**Comment by skandasoft** [comment]
![image](https://cloud.githubusercontent.com/assets/9875379/10666543/d85fcd1c-7897-11e5-83c0-66f07a6d95fb.png)
you shoud be seeing this tool bar if you have the latest...

**Comment by skandasoft** [comment]
would be happy to hear the feedback. Since I don't see any, assuming things are fixed
