### ISSUE TITLE
Location bar is not a standard text field

### ISSUE THREAD

**Issue by thSoft** [skandasoft/browser-plus#48]
Standard text field operations (clipboard, select all) do not work in the location bar.
Versions:
Atom 1.1.0
browser-plus 0.0.53
OS X 10.10.5

**Comment by skandasoft** [comment]
can you check if some other package is hijacking ..use the key-binder package to check what happens when you do the select all / clipboaard..

**Comment by skandasoft** [comment]
Closing it since there are no updates..feel free to re open
