### ISSUE TITLE
Zoom font when ctrl scrolling.

### ISSUE THREAD

**Issue by reverland** [skandasoft/browser-plus#49]
Any possibilitiy to support [zoom font when ctrl scrolling.](https://github.com/atom/atom/pull/3737/files)

the default font size may not work well.

![screenshot from 2015-11-20 21 41 13](https://cloud.githubusercontent.com/assets/1418726/11301130/9a2fa824-8fcf-11e5-877a-47e45744f4ee.png)

**Comment by skandasoft** [comment]
Planning to add a plugin system..that way more feature can be added as plugin by contributors

**Comment by jamesalbert** [comment]
I have this feature ready for merge. Once the word find commit is merged, I'll do a pull request for the zoom

**Comment by skandasoft** [comment]
check out the https://atom.io/packages/browser-plus-zoom. Thanks to @jamesalbert
