### ISSUE TITLE
wrappedOpener is deprecated.

### ISSUE THREAD

**Issue by OttoRobba** [skandasoft/browser-plus#5]
If you would like your pane item with class `HTMLEditor` to support modified behavior, please implement a `::onDidChangeModified()` method. If not, ignore this message. `::on` methods for items are no longer supported.
```
wrappedOpener (/usr/share/atom/resources/app.asar/src/workspace.js:523:18)
Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:433:22)
Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:366:19)
Object.preview (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:209:21)
Object.toggle (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:152:9)
atom-workspace.atom.commands.add.preview-plus:preview (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:81:68)
```

**Comment by OttoRobba** [comment]
If you would like your pane item with class `HTMLEditor` to support title change behavior, please implement a `::onDidChangeTitle()` method. `::on` methods for items are no longer supported. If not, ignore this message.
```
wrappedOpener (/usr/share/atom/resources/app.asar/src/workspace.js:518:18)
Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:433:22)
Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:366:19)
Object.preview (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:209:21)
Object.toggle (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:152:9)
atom-workspace.atom.commands.add.preview-plus:preview (/home/otto/.atom/packages/preview-plus/lib/preview-plus.coffee:81:68)
```

**Comment by skandasoft** [comment]
I am not sure if there is any of this on the code..will wait for it to happen and see what impact it makes...will keep the issue open for now.

**Comment by OttoRobba** [comment]
You don't have to wait - you can start Atom with the --one flag and see what happens.

**Comment by skandasoft** [comment]
wonderful...I found every thing find with browser plus..so closing it.
