### ISSUE TITLE
Why is youtube blocked by default?

### ISSUE THREAD

**Issue by jamesalbert** [skandasoft/browser-plus#54]
It seems to work fine on my end, just wondering

**Comment by skandasoft** [comment]
youtube take much off my time :). It is configurable..you can go to the setting for browser-plus and specify which web site need to blocked..by default I have it as youtube I think.again there is a browser-plus-block sample plugin..if you wanted to make it more elobrate (maintain time between which you needed to block kind of stuff and keywords etc) and release a plugin
