### ISSUE TITLE
add a option to open file in browser with web-url on starting

### ISSUE THREAD

**Issue by netmou** [skandasoft/browser-plus#57]
i think there should be a option   "web-root"  in the plugin setting 
such as web-root:localhost/../xxx/
so that i can open a file in browser width web-url on starting like this:

![111](https://cloud.githubusercontent.com/assets/7068058/12009594/267aa0e8-acba-11e5-8487-b43ef06afc8f.jpg)

based on this idea php and jsp file can be previewed  easily

**Comment by skandasoft** [comment]
Yes there is settings for that and it is called home page.check it out.

**Comment by netmou** [comment]
yes it's exist,but can't open file using web-path on starting

**Comment by skandasoft** [comment]
check out the open-in-browsers package(https://atom.io/packages/open-in-browsers) with pp package(preview-plus https://atom.io/packages/pp)
