### ISSUE TITLE
Uncaught Error: Bootstrap's Javascript requires jQuery

### ISSUE THREAD

**Issue by yaffeweb** [skandasoft/browser-plus#60]
When loading the dev tools, the console says that bootstrap.min.js basically can't find the Jquery. If you load it in firefox and use it's dev tools or firebug, this issue isn't present. I can't tell if the Error is actually causing a problem withing BP or not. Opera's dev tools show no issue either.

**Comment by skandasoft** [comment]
it is just a console thing..
