### ISSUE TITLE
Should have "Live" toggle activated by default

### ISSUE THREAD

**Issue by benjaminb10** [skandasoft/browser-plus#61]
When we open the embedded browser with ctrl+alt+o
The "Live" toggle should be activated by default.
Or at least have the option to activated it by default in the settings of the package ;)

**Comment by skandasoft** [comment]
This is simply a browser. If you are looking for live reload options...check out the pp(preview-plus) package
https://atom.io/packages/pp

**Comment by akhilcb** [comment]
I need this feature by default too. Is there a command available to do this so that we don't have to manually click live always. Please let me know if anyone has any solution.
