### ISSUE TITLE
First user,and have questions

### ISSUE THREAD

**Issue by Javacym** [skandasoft/browser-plus#64]
when open Favoritize url is split a new pane, is there a way open is the same pane?

and 
![image](https://cloud.githubusercontent.com/assets/13167757/14074610/d50fe8ba-f504-11e5-94fd-64cd08f712dc.png)
ICON of website seems  work a little bug
Thanks a lot

**Comment by skandasoft** [comment]
fixing the favorites from the window menu(browser-plus:fav).
