### ISSUE TITLE
Wrapping content to fit window width

### ISSUE THREAD

**Issue by JLCCI** [skandasoft/browser-plus#65]
Thanks for the amazing package, it' incredibly useful.

Not sure how much work it would be but would you consider adding tools to automatically wrap pages to fit within the window width (and perhaps scale the images)? Scrolling sideways is the only small issue with your otherwise great plugin.

Keep up the good work.

**Comment by skandasoft** [comment]
check out browser-plus-zoom package(https://atom.io/packages/browser-plus-zoom)
