### ISSUE TITLE
Browser-plus height is about one-fifth what it should be

### ISSUE THREAD

**Issue by fusion809** [skandasoft/browser-plus#71]
Hi,

I've just started using this package on my 64-bit Arch Linux installation of Atom and noticed this graphical bug:

![](http://imgur.com/pMvVFmj.png)

note how the browser-plus pane (on the far right, if that's somehow not obvious by this screenshot) is about 1/3rd-1/5th the height it should be. My `browser-plus` settings are all the default (I haven't changed them since installing this package). 

Thanks for your time,
Brenton

**Comment by rodrigobr92** [comment]
Same problem here. Using Arch Linux also. Everything else is perfect with atom and this package.

**Comment by gscacco** [comment]
Same problem for me. I'm using Antergos (arch based distribution)

**Comment by skandasoft** [comment]
how is possible. some thing to do with the css..can you check the f12..I don't have a linux

**Comment by fusion809** [comment]
Here's a screenshot showing what opening the developer tools for browser-plus shows on Arch:

![](http://imgur.com/1luYqPo.png)

**Comment by fusion809** [comment]
Something that maybe relevant is that Arch Linux uses freetype 2.6.3 and hence we Arch users must compile Atom against a later version of Electron in order for it to build properly (per [Atom issue 11198](https://github.com/atom/atom/issues/11198)). For me I compiled Atom against Electron 0.36.12

**Comment by rapgenic** [comment]
I have the same problem, and I use Antergos, too. I fixed by adding
```css
div.browser-plus webview {
  height: 100%;
}
```
in the default styles.less file

**Comment by fusion809** [comment]
I ran Atom 1.7.4 on my Ubuntu 16.04 installation and had the same issue with browser-plus. But, rapgenic's fix worked on this installation.
