### ISSUE TITLE
Cannot read property 'sendToHost' of undefined

### ISSUE THREAD

**Issue by gruppler** [skandasoft/browser-plus#73]
I see this error in the console every time the page loads.

![break](https://cloud.githubusercontent.com/assets/301190/15412797/a1cfaa36-1df8-11e6-8877-be4ed7db42c2.png)
![error](https://cloud.githubusercontent.com/assets/301190/15412799/a46372a0-1df8-11e6-842c-91b582e64956.png)

**Comment by Jonahss** [comment]
ooh, I think I know how to fix this one!
My console reports `ipc module is deprecated. Use require("electron").ipcRenderer instead`
So that probably needs to be updated for you.
I'll try to submit a fix, but I'm having trouble building the project.

**Comment by skandasoft** [comment]
With the latest patches, the ipc stuffed is removed(will be added the node integeration soon for a richer functionality). There should not be any more issues around this. Feel free to reopen if it exist with latest patch.
