### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by gruppler** [skandasoft/browser-plus#74]
I keep seeing this error in the console, and it's preventing my JS to run:
`Uncaught ReferenceError: jQuery is not defined`

Here's the code where it's breaking:

    var jQ, href, ipc;

    if (window['browser-plus'] == null) {
      ipc = require('ipc');
      href = location.href;
      if (href.startsWith('data:text/html,')) {
        href = null;
      }
      ipc.sendToHost('startup', {
        href: href,
        title: document.title
      });
      jQ = jQuery.noConflict();

**Comment by skandasoft** [comment]
Please check the latest patch.
