### ISSUE TITLE
Browser Plus doesn't load, cannot uninstall, cannot reinstall

### ISSUE THREAD

**Issue by larpo1** [skandasoft/browser-plus#76]
Uninstalling “browser-plus” failed.
Failed to delete browser-plus: Does not exist

and yet: 

http://cl.ly/1y1C3k1r1X0r

**Comment by larpo1** [comment]
installing from the command line appears to succeed: 
$ apm install browser-plus
Installing browser-plus to /Users/larpo/.atom/packages ✓

but then ctrl+alt+o does nothing

**Comment by larpo1** [comment]
And: http://cl.ly/2E0j3C462P30

**Comment by skandasoft** [comment]
go to the package folder and delete the browser-plus and reinstall

**Comment by larpo1** [comment]
no joy - added and removed twice. nothing.

**Comment by skandasoft** [comment]
try installing again. can you check in the packages folder if the browser-plus is there. then go ctrl+alt+p and start typing browser..you should see there..may be ctrl+alt+o is taken by some body else.

**Comment by skandasoft** [comment]
hope that fixed it. Feel free to reopen
