### ISSUE TITLE
FYI: web-browser package deprecated for browser-plus

### ISSUE THREAD

**Issue by mark-hahn** [skandasoft/browser-plus#8]
I changed the repo and atom.io readme for web-browser package to say it is not supported any more and use browser-plus instead.  I'd be happy to transfer the ownership of web-browser or do anything else if desired.

This means browser-plus better be supported well or I'll be pissed.  (grin)

**Comment by skandasoft** [comment]
I hope I can...Hoping you can chip in as well if you found some thing.
