### ISSUE TITLE
How to build resources?

### ISSUE THREAD

**Issue by Jonahss** [skandasoft/browser-plus#81]
Hi, I'm looking at browser plus and trying to make some fixes/changes.

How do I build browser-plus-client.js? I know somehow it gets built from ipc.js but don't have the code for it.

**Comment by skandasoft** [comment]
Thanks for reaching out. I am planning to keep the browser-plus basic and enhancments to browser-plus can be done as packages. Check out the https://atom.io/packages/browser-plus-zoom to see how browser-plus functionality can be enhanced. Feel free to reach out you have any questions.
