### ISSUE TITLE
Browser size does not fit panel size

### ISSUE THREAD

**Issue by manulaiko** [skandasoft/browser-plus#89]
When I start Browser-plus its size doesn't fit panel's size, resizing panel doesn't fix it. It works well with atom 1.8.0

Here is a short video: https://www.youtube.com/watch?v=-NMqkbheDos&feature=youtu.be

Atom version: 1.9.0-beta
Browser-plus version: 0.0.67

**Comment by skandasoft** [comment]
I cannot see the video..since it is marked private. Also can you check the latest patch.

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
