### ISSUE TITLE
Feature Request: Automatically open Jekyll post at http://localhost:4000/<PERMALINK>

### ISSUE THREAD

**Issue by fusion809** [skandasoft/browser-plus#93]
Hi,

When editing a Jekyll post (with either Asciidoc / Markdown / Textile grammar) I would like the "Open Browser-Plus" context menu (opened by right-clicking the post) to open browser-plus to `http://localhost:4000/<PERMALINK>`, where `<PERMALINK>` is the `permalink:` field value in the post's front-matter. If you are confused as to the format of such a post here's a snippet (including front matter) from a Asciidoc post of mine:

```ad
---
date:         2016-07-08 +1000
title:        "How to Create Your Own Arch Linux Package Repository"
permalink:    /how-to-create-archlinux-repository/
categories:   archlinux, package-development, software-repositories
---

*Arch Linux* is my favourite Linux distribution (LD), especially when it comes to building packages. This is because the PKGBUILD format is very intuitive, simple and written in my favourite programming language &mdash; Shell. Writing a PKGBUILD also does not require an awful lot of preliminary knowledge, unlike the other Linux packaging source file written in Shell, that I have a fair amount of experience with, ebuilds. They require you understand eclasses, in a fair degree of detail, in order to effectively and efficiently write them. The fact that Arch Linux package development only requires that you have a functioning PKGBUILD and does not require a whole intricate directory of syntactically-correct source files to be written by you, the packager, makes Arch Linux packages easier to develop compared to say Debian packages. The packaging source files they most closely resemble is SlackBuilds for Slackware packages, which I have fairly minimal experience with.
```

in that case browser-plus should open up to http://localhost:4000/how-to-create-archlinux-repository/. localhost:4000 is the default location of your locally-running Jekyll server. 

Thanks for your time,
Brenton

**Comment by skandasoft** [comment]
check the combination of package pp and open-in-browsers (https://atom.io/packages/pp & https://atom.io/packages/open-in-browsers)
